project:
  type: book
  output-dir: _book
  
book:
  title: "A Compilation of Baha'u'llah's Writings"
  subtitle: "Translated Using GPT 4"
  author: "Baha'u'llah"
  reader-mode: true
  downloads: [pdf, docx]
  search: true
  
  
  page-footer: 
    left: |
      Created by the Baha'i Translation Project
    right: |
      Translations used were created with GPT 4
      
  chapters: 
    - index.qmd
    - part: "Writings Revealed in the Year 1858"
      chapters: 
        - hidden-words-arabic.qmd
        - hidden-words-persian.qmd
    - part: "Writings Revealed in the Year 1860"
      chapters:
        - seven-valleys.qmd
    - part: "Writings Revealed in the Year 1861"
      chapters: 
        - kitab-i-iqan.qmd
    - part: "Unknown Dates Prior to Declaration in 1863"
      chapters: 
        - lawh-i-madinatut-tawhid.qmd
    - part: "Writings Revealed in the Year 1866"
      chapters: 
        - suriy-i-damm.qmd
    - part: "Writings Revealed in the Year 1868"
      chapters: 
        - kitab-i-badi.qmd
        - tablet-of-the-branch.qmd
    - part: "Writings Revealed in the Year 1869"
      chapters: 
        - suriy-i-haykal.qmd
    - part: "Writings Revealed in the Year 1870"
      chapters: 
        - lawh-i-ahbab.qmd
    - part: "Unknown Dates in the Edirne Period"
      chapters: 
        - lawh-i-khalil-1.qmd
        - lawh-i-salman-1.qmd
        - suriy-i-bayan.qmd
        - suriy-i-qamis.qmd
    - part: "Writings Revealed in the Year 1873"
      chapters: 
        - kitab-i-aqdas.qmd
    - part: "Writings Revealed in the Year 1891"
      chapters: 
        - lawh-i-bisarat.qmd
        - lawh-i-dunya.qmd
        - book-of-my-covenant.qmd
    - part: "Unknown Dates in the Akka Period, 1868-1892"
      chapters: 
        - lawh-i-baytul-adl.qmd

  output-file: "Bahaullah Compilation GPT"
    
  
format:
  html:
    theme:
      - minty
    fontsize: 10pt
    number-depth: 6
    toc-depth: 6
  
  pdf:
    documentclass: scrbook
    output-file: "Bahaullah Compilation GPT4"
    fontsize: 9pt
    number-depth: 6
    toc-depth: 6
    
  docx:
    reference-doc: reference1.docx
    toc-depth: 1
    number-depth: 6