project:
  type: book
  output-dir: _book
  
book:
  title: "A Compilation of Baha'u'llah's Writings"
  subtitle: "Translated Using GPT 4"
  author: "Baha'u'llah"
  reader-mode: true
  downloads: [pdf]
  search: true

  page-footer: 
    left: |
      Created by the Baha'i Translation Project
    right: |
      Translations used were created with GPT 4
      
  chapters: 
    - index.qmd
    - part: "Writings Revealed in the Year 1858"
      chapters: 
        - hidden-words-persian.qmd
    - part: "Writings Revealed in the Year 1860"
      chapters:
        - seven-valleys.qmd
    - part: "Writings Revealed in the Year 1861"
      chapters: 
        - kitab-i-iqan.qmd
    - part: "Writings Revealed in the Year 1868"
      chapters: 
        - kitab-i-badi.qmd
        - tablet-of-the-branch.qmd
    - part: "Writings Revealed in the Year 1891"
      chapters: 
        - book-of-my-covenant.qmd

  output-file: "Bahaullah Compilation GPT"
    
  
format:
  html:
    theme:
      - minty
    fontsize: 10pt
  
  pdf:
    documentclass: scrbook
    output-file: "Bahaullah Compilation GPT4"
    fontsize: 9pt