# Ahsan al-Qasas (The Best of Stories) {#sec-ahsan-al-qasas .unnumbered}

## Introduction

This is the Book of the Supreme Heaven, entitled the Best of Stories, an explanation of the Sura of Joseph.

"Aḥsan al-Qaṣaṣ" "Qayyūm al-Asmā'" from the blessed works of His Holiness the Most High (His Holiness the Báb).

## The Sura of Sovereignty (Surah 1) {#sec-the-sura-of-sovereignty}

*Surah of Joseph Verse 1: "Alif, Lām, Rā. These are the verses of the clear Book."*

And it is forty-two verses, Shirazi

In the name of God, the Most Merciful, the Most Compassionate

Praise be to God Who has sent down the Book upon His servant with truth, that it may be a light for the worlds, blazing and bright. This is indeed the path of 'Ali, established in truth before your Lord, already ordained in the Mother of the Book, straight and true. And indeed, in the Mother of the Book, with Us, it is for 'Ali, and upon the greatest truth, it was with the Merciful, wisely ordained. And it is the truth from God, and upon the pure religion, it was inscribed in the Mother of the Book, around the Mount, recorded. Indeed, this is the truth, the path of God in the heavens and the earth. So whoever wishes may take a path to God in truth. Indeed, this is the firm religion, and sufficient is God, and those with Him, knowledgeable of the Book, as witness. Indeed, this is the truth, upon the greatest word from God, the Ancient, sent around the fire. This is indeed the secret in the heavens and the earth, and upon the wondrous matter by the hands of God, the High, it was truly written in the Mother of the Book. God has decreed to bring forth that Book in the interpretation of the Best of Stories, from Muhammad, son of Hasan, son of 'Ali, son of Muhammad, son of 'Ali, son of Musa, son of Ja'far, from Muhammad, son of 'Ali, son of Husayn, son of 'Ali, son of Abi Talib, upon His servant, to be God's proof from the Reminder upon the worlds, compellingly. I bear witness to God as He bears witness to Himself, that He is the truth, there is no god but He, and the angels, guardians around the Reminder with justice, there is no god but He, and He is God, knowledgeable of everything. The pure religion is this Reminder, whole. So whoever desires Islam, let him submit his affair, for God will write him in the book of the righteous, submitted. And upon the pure religion, it was with truth, praiseworthy. And whoever disbelieves in Islam, God will not accept from him any of his deeds on the Day of Judgment, not even a little, on the truth, by the truth, nothing. And it is right upon God to burn him with the fire of God, the wondrous, by the decree of the Book, from the decree of the Gate, destined. God, there is no god but He, and He is God, watchful over the believers. God, there is no god but He, and He is God, a witness over the believers. God, there is no god but He, and He is God, knowledgeable of the believers. God, there is no god but He, and He is God, encompassing the worlds. And God will not accept from anyone any deed unless he comes to the Gate, prostrating through the Gate. The Ancient God, praiseworthy around the Gate. God has authorized you upon truth, so prostrate and draw near, for in a drop of water, the fire was, God the truth was, prostrated upon the earth in truth, witnessed. O assembly of kings and sons of kings, turn away from the kingdom of God, all of you, upon the truth, beautifully. O king of the Muslims, then support after the Book, our greatest Reminder, in truth, for God has decreed for you and those barefoot around you, in valuation, upon the path, standing in truth, questioned. O king, by the truth of God, if you oppose with the Reminder, God will judge you among kings with fire on the Day of Judgment, and today you will not find, apart from God, the High, on the truth, by the truth, any helper. O king, purify the sacred earth from the people who reject the Book before the day the Reminder comes suddenly by the permission of God, the High, upon the strong matter, severely. And God has written upon you to submit the Reminder and its command, and to make the lands subservient in truth by His permission, for you are in this world, upon the kingdom, merciful, and in the hereafter, among the people of the garden of pleasure around the holy, you were dwelling. O king, let not the kingdom deceive you, for every soul will taste death, it was by the truth, upon the truth, written from the judgment of God, and be content with the judgment of God, the truth, for the kingdom in the Mother of the Book, concerning the Reminder by the hands of God, was truly recorded. And support God with yourselves and your swords in the shadow of this greatest Reminder for this pure religion, strong in truth, upon the truth. O minister of the king, ease off from God, there is no god but He, the just truth, and remove yourself from the kingdom, for we shall inherit the earth and those upon it, by the permission of God, the Wise, and indeed, it was with truth upon you and upon the kingdom, witnessed. And we have guaranteed for yourselves, by the permission of God, to obey the Reminder with pure truth, that for you in valuation, in the garden of Eden, is a great kingdom upon the truth. And your kingdom is vain, and God has made the enjoyment of this world for the disbelievers, and with God.

Your sovereignty, Hasan of the lineage, has indeed been in truth upon truth from ancient times, and indeed, for us in the garden of eternity, is a lofty kingdom. We grant it to whomsoever we will of our servants, those who were in this cause with God and for His signs, supporters in truth. O assembly of kings, convey our signs to the Turks and the land of India swiftly in truth upon truth, and beyond its lands, from the east of the earth to its west, strongly in truth upon truth. O servants of the Merciful, indeed, God has not created you and has not provided for you except for a matter that was with God in the Mother of the Book, great in truth upon truth. And follow what God has revealed to us of the decrees of the Gate in that Book, submitting to God and His command, pleased upon the truth. And know that if you support God, He will support you on the Day of Judgment with the greatest reminder, on the path, a noble support. By God, if you do well, you do well for yourselves; and if you disbelieve in God and His intentions, we are, by God, beyond creation and sovereignty, rich in truth. O people of the earth, whoever obeys the remembrance of God and this Book, has indeed obeyed God and His allies in truth, and indeed, in the hereafter, he is among the people of the Garden of Pleasure with God, written. And indeed, we have set the mountains moving on the earth and the stars upon the throne, around the fire, in the water's pole, from the presence of the reminder with God, the truth. And none of you will forsake another, and He is the Dominant over His servants, and He is God, knowledgeable of everything.

## The Sura of Scholars (Surah 2)

*Surah of Joseph Verse 2: Indeed, We have sent it down as an Arabic Qur'ān that you might understand.*

In the name of God, the Most Merciful, the Most Compassionate,

Alif Lam Ra. These are the verses of the clear Book, Alif Lam Mim. That Book, from God, the Truth, concerning the Reminder, was revealed in truth around the fire. Indeed, we have made the verses in that Book clear, a reminder and good news for the servants of the Merciful, for those who are with God and His signs, faithful in truth, who do not compel their parents and deter them with truth from deviance at the edge of the Book's knowledge as a mandate. Just, who was with truth harsh upon the kingdom, those who fear their Lord, for a day that was in truth harshly written in the Mother of the Book, we fear from the Merciful on a grim day, a name inscribed in the Mother of the Book, a day when no soul controls anything for another soul, and the command then is for God, the Most High, and God was over everything a Witness.

Indeed, we have made the verses an argument for Our word over you. Can you produce a chapter like it? Bring your proof if you are truthful with God, seeing. By God, if humans and jinn united to produce the like of a sura from this Book, they could not, even if they supported each other. O assembly of scholars, fear God in your opinions from this day, for the Reminder among you from Us has been a ruling and witnessing truth. And disregard what you take from other than the Book of God, the Truth, for you stand accountable upon the Straight Path in valuation. And God has made suspicion in all the tablets a clear sin. And perhaps God will pardon you for what you have earned for yourselves before this day, for He is Forgiving, Merciful to the repentant.

And God has forbidden you from ruling on anything other than the pure knowledge from this Book, without truth and exertion. And indeed, We have sent down to you this Book witnessed in truth, so you may learn from what God has decreed in our favor, far from falsehood. And you have in the valuation on the Straight Path a position accountable in truth, truly. God asks His servants about what they do in the religion of God without true judgment in that Book, concealed. Soon, God will show you the signs of the Reminder suddenly on Earth in truth, imminent.

O assembly from the People of the Book, fear God and do not be deceived by your knowledge, and follow the Book from the Reminder in truth, by God, the truth, no soul that follows it but follows all the scriptures sent down from the heavens from God, the Truth, and God is aware of what you do. And no soul that denies the Book but denies the Oneness of the Merciful and disbelieves in the prophets and the scriptures sent from the heavens in truth, and their abode was the fire by truth, and God decreed the judgment in the Mother of the Book, executed in truth. And if God willed, He could have guided all people, and God has made our signs clear to the worlds. And the Reminder is the truth from God in truth, and God was over everything Powerful.

And when people disbelieved in our signs, they were ungrateful to God, the Most High, and those who disbelieved will know their place in a valley of the confined, which God named in the Mother of the Book as Hell. And indeed, we by truth make you taste the heat of Hell and your replacement from the toxic fire, decreed in the Book. This is indeed the truth from God as a recompense for your stubbornness with our signs and the remembrance of God, the Most High. This is the recompense like what you were in misery with God and with our signs, and the command of your Lord, the Merciful, is truth, and the promise of God was indeed enacted in truth. Praise be to God who revealed the light from Himself upon our servant to be a straight path in the worlds in truth, and indeed, We reveal to you what God has revealed to us; you were indeed high in the Mother of the Book with God. And what is in the heavens and the earth is by truth, and God forgives whom He wills and punishes whom He wills, and He is God, Powerful over everything. Fear the day you will return to God, and there is no judgment but His; there every soul is recompensed for what it has earned, and indeed, We do not wrong a thing.

Those who believe in the Reminder sent down to him from his Lord and the believers, each believes in God and His signs and do not differentiate between any of His signs, and the Muslims say by truth, "Our Lord, we have heard the call of God's Reminder and obeyed, so forgive us, for You are the truth, and to You is the return by truth, O believers ! We indeed do not burden you except with what you can bear, and the kingship was God's alone, God wants to lighten your punishment and send His mercy upon you, and no soul has earned anything except we have written it by the judgment of the Book, preserved. Say, 'Our Lord, God, our truth, there is no deity but He, so forgive us with Your mercy and have mercy on us, for You are our Patron, and write for us the return to You in truth by truth, God, there is no deity but He, created the letter Alif strong on the command, God, there is no deity but He, has decreed the letter Lam for His judgment on the judgment of the Book, God, there is no deity but He, has made the letter Ra for the expansion of His command as He wills in the Mother of the Book around the fire, decreed in truth."

## The Sura of Faith (Surah 3)

*The Surah of Joseph Verse 3: We relate to you, \[O Muḥammad\], the best of stories in what We have revealed to you of this Qur'ān although you were, before it, among the unaware.*

We sent it down as an Arabic Qur'an so that you may understand. Ta-Ha. God has indeed sent down the Qur'an to His servant so that he may teach people that God has power over all things. He who sent down the Criterion in Arabic, without any crookedness, upon His servant, purely and truly as a revelation to show you His signs and the interpretation of the narratives along the right and straight path. Indeed, this is the path of 'Ali in the heavens and on earth, uniquely true from God, the Most High. He is God, there is no deity but He, He has sent down to you this Book with the greatest Reminder, affirming the messengers and what God has revealed in the scriptures; there can be no alteration to the words of God, the Truth, and it is the truth in the Mother of the Book, inscribed around the fire.

This Book, if it had been from other than God, the Truth, they would have found in it much discrepancy. And glorified is God, our Lord, nothing is hidden from Him on the earth or in the heaven, and we have recorded everything in this Book by God's permission, hidden and truly inscribed from God. And those who disbelieve in the exalted door of God, we have prepared for them a painful punishment by the true judgment of God, and He is God, mighty and wise. Indeed, we have sent down to Our servant this Book from God in truth, and made the verses therein precise and unambiguous, and none knows their interpretation except God and those of Our servants whom we choose, the devoted ones.

So ask the Reminder for its interpretation, for he has been, by God's grace, knowledgeable of its verses by the decree of the Book. Our Lord, we praise You after You have guided us, and grant us mercy from You, as You were capable and giving by truth. Indeed, those who disbelieve in the greatest Reminder of God, their wealth and their children will not avail them against God in the least, and they have no power apart from God; those are the companions of the fire, by the just decree of God, abiding therein forever and ever. God has indeed supported with His help whomever He wills among His servants, and we have indeed made the love of women, sons, and wealth appear desirable to you, all of which are barriers to death. And God has indeed made good provision for those who support the remembrance of God, the Most High, with their hands, their tongues, and their wealth, God the Self-Sufficient, and He is God, mighty and praiseworthy.

When the People of the Book argue with you about something, say, "I have no knowledge except what my Lord has taught me; indeed, I have submitted my face to God, the creator of the heavens and the earth." And whoever is arrogant in worshiping Him by turning away from My remembrance, it is right for God to burn him with the greater fire, justly deserved by truth upon truth. And you desire nothing except what God wills for you; indeed, He has been knowledgeable and wise. And the polytheists among you say, "The fire will not touch us except for a few days"; when we gather them on the Day of Judgment around the fire, they will testify against themselves that the punishment of their Lord had been inscribed in the Mother of the Book from the Door of old. And sovereignty belongs to God; He grants sovereignty to whom He wills and withdraws it from whom He wills, and He is God, powerful over all things. And we indeed humiliate the disbelievers as they wish and honor the believers as they wish, and God has indeed placed the good in your hands by truth, and God has placed your hands in the Mother of the Book, raised right. And indeed, in the creation of the night and day and their intermingling, and the bringing forth of the living from the dead and the dead from the living, are signs for the greater remembrance of God. Thus, it has been inscribed in the preserved tablet with God, the Most High.

O servants of the Merciful, do not take disbelievers as allies instead of the believers who preceded you. And whoever meets God with disbelief in the Book and this Reminder, then from God he will have nothing, and the Truth Himself has warned you, and to God, the Truth, is the return of all worlds if you fear your Lord, the Merciful, about what your hands have earned from the work of Satan, then hasten to forgiveness from your Lord before the day you find your deeds present before you. And God knows what is in the heavens and on the earth by truth, and He is God, rich over all worlds. O servants of God, the Merciful Himself warns you not to say about God except the truth, and He knows what you conceal in yourselves and what you declare, and He has indeed been kind and merciful to His servants on the truth by truth. O people, if you believe in God alone, then follow me in the greater remembrance of your Lord so that God may forgive your sins, and God has indeed been forgiving and merciful to the believers. And we indeed choose the messengers by Our word and favor their descendants with the great remembrance of God, some over others by the decree of the Book, hidden. And we indeed have given you the judgment of the doors by the permission of God, the All-Hearing, and He is God, a witness over all things. And we indeed sent Our spirit to Mary and accepted the vow of the wife of Imran, dedicated by God, the Most High, and He is God, knowledgeable of His believing servants. And we indeed gave the prophet Zechariah the good news with Our name, John, affirming the word of God, the greatest; this is from God, and we make him by that a master and a keeper in the Mother of the Book. The creation of the worlds is like Our command; when we want to say to it, "Be," it becomes, in the Book of the praised God, existing around the fire. And God has taught you the knowledge of the Book from the Criterion, the Gospel, the Torah, the Psalms, and what is beyond them from the scriptures, and you have indeed been at your Lord's door at the point from the concealed 'Ba,' stopped. And we indeed have inspired you with news of the unseen and sent down to you this Book in truth, and we have forbidden you the impurities and made lawful for you the good things so that people may believe in your remembrance, hoping for the honor of God's ancient religion by truth. And God was knowledgeable of all things. And those who think that they can harm you with something from knowledge have indeed fallen from the sky to a dead, uprooted earth, and God was a witness over all things. And God has made your being touched by our beings, and your existence a trinity of the light of God's ancient essence, our Lord, and He is God, powerful over all things. And the polytheists plotted against themselves in your remembrance and will not harm except themselves, and God has indeed fulfilled His promise, and I am purifying you and causing you to die and raising you to God, the Truth, and you will judge by God's permission on the Day of Judgment in what people differ in the remembrance of God, the Most High, and God was a witness over all things. Some from the city said, "We are the supporters of God"; when the Reminder came to them suddenly, then they turned away from our support, and God is my Lord and your Lord, the Truth, so worship Him, and this is the straight path by your Lord, so soon God will judge between people by truth, then they will not find in themselves any distress from God's pure judgment, and the matter was decreed in the Mother of the Book. And when the matter reaches intensity, argue by God's permission with the polytheists, and say, "Come, let us call upon our Lord, who is no deity but He, by ourselves and yourselves, and God is indeed the Truth, a witness over us, and He is God, knowledgeable of all things. By your Lord, if you confront the disbelievers, and God is indeed the Truth, a witness over us, and He is God, knowledgeable of all things. By your Lord, if you confront the disbelievers, people look to the edge of the sky, and we have sent down upon them by God's permission a lightning bolt of firestone, and if not for your prayer, the earth and some upon it would have been burned, and God was powerful over all things. Say, O People of the Book, believe in a word from God, equal between me and you, that you worship none but Him, and do not associate anything in His worship, and do not take from among you some as lords apart from God; He is one God, like whom there is nothing, and He is God, a witness over all things.

## Surah of the City (Surah 4)

*Surah of Joseph Verse 4: \[Of these stories mention\] when Joseph said to his father,1 "O my father, indeed I have seen \[in a dream\] eleven stars and the sun and the moon; I saw them prostrating to me."*

In the name of God, the Most Merciful, the Most Compassionate

We relate to you the best of stories through what We have revealed to you of this Qur'an, though you were unaware of it before. Truly, We have clarified the stories for those who desire us at the door, loving and responding. And indeed, We have sent down the Book in truth upon truth so that people might be in accordance with the Name of the Remembrance written in the Book.

We have indeed sent down the Book to every nation in their language, and We have indeed sent down this Book in the language of the Remembrance truly and wonderfully. It is indeed the truth from God and in the Mother of the Book, decreed among the most eloquent of Arabs. It is the most eloquent among the most articulate, and it is the greatest talisman in truth, and it was in the Mother of the Book marked as a talisman.

We have indeed made you a sun over the worlds and a luminous moon, a chaste herald, and a strong pillar over the worlds, that perhaps the people would be guardians of God's signs in truth upon truth. But the people were not pleased with the true signs of God, and the people were strangely against God and His decrees.

O servants of God, did not our servant show you the true promise concerning what God intended for you in the proper religion? And indeed, God has made the signs our signs, and concerning the matter of the Remembrance, the decree of the Book was written in the Mother of the Book. This is one of them for anyone who has a covenant from the Merciful around their neck, truly and rightly, and has entered into that gate by the permission of God, the Praiseworthy, pure and cleansed.

O people of the city, you are the polytheists against your Lord if you believed in Muhammad, the Messenger of God, and the seal of the prophets, and his book the Criterion, which falsehood cannot approach. Indeed, We have sent down to Our servant this book by His permission, just like it, if you do not believe in it, then your faith in Muhammad and the book before was indeed a lie witnessed by God. And if you disbelieve in it, then your disbelief in Muhammad and his book was certainly known to yourselves truly and certainly.

O people of the city and those around it from the Bedouins, what is wrong with you, how did you disbelieve in Muhammad openly and wrongly after his death? Did not God and His prophet take from you a covenant regarding the guardianship of His successor in many places on the earth truly and abundantly? If you believed in God, who there is no deity except He, then what is wrong with you, how do you judge for yourselves with other than what God revealed in His true book preserved?

By your Lord, if you do not believe in our remembrance and this book, then be certain that your abode is the fire wherein you will dwell forever, and you will have no helper from God the Most High on the day of judgment. Indeed, some souls among you have died in disbelief before, and you did not believe in Muhammad nor those around him after his ascension except you disbelieved in his successor. What is wrong with you, do you not contemplate the Qur'an as a true revelation? God indeed promises you Paradise and Satan invites you to your religion which leads you to Hell.

So whoever among you wishes may believe and whoever wishes may disbelieve, and indeed God is free of need from all the worlds. And indeed, the power is with God, the Almighty of old. O people of the city, fear God on a day when you will not be able to do anything for yourselves, and indeed the decree from us was written in truth upon truth. What is wrong with you, how did you disbelieve in God, your creator, who there is no deity except He, who created you and provided for you from His bounty, and indeed He has always been a witness over you.

Will you not then contemplate the Qur'an as a revelation? Will they not then contemplate the Criterion as an interpretation? Fear God from whom we take on the truth severely, if you were in what you were and do not return to the high remembrance of God truly and soon. Then God will show you in the reckoning a fire that has encompassed yourselves; there you will find no helper apart from God the Most High. Have you believed in something other than the true God, and God has always been a witness over all things.

Have you believed in something other than the true God? God has always been a witness over all things. Have you believed in two souls other than the true God, while God encompasses all things? O delight of the eye, strike upon the people of the city a decisive blow. God has decreed for one of them two elevated gardens around the door, each with trees. One garden is watered from two basins, and the other drinks from two cups. Both are by God\'s permission, surrounded by fire and stopped at two waters. There are also two rivers in the land of the two Wests, with whales in one of the bays.

Then he asked his companion among the first two, "Which of you will take charge in the other two?" And in those two hours standing, a month on the disbelief with certainty for the souls themselves and the two souls thereafter, by the true God, then connect with the truth. Which of the two souls in the two parties was praiseworthy around the fire? Indeed, the truth was recognized in the Sacred Mosque, seeing the state in the greater truth. Have you disbelieved in the one who created you from dust, then from a sperm-drop, then fashioned you into a man? O people of polytheism, why have you made your hardship with the door another door? The true God has indeed set your seat by the fire. The book rules, settled and released.

## Surah 5
