# **Asl-i-Kullu'l-Khayr (Essence of All Good)** {#sec-asl-i-kullul-khayr .unnumbered}

He is the Most Exalted, the Most High.

1 The foundation of all goodness is reliance upon God, submission to His command, and contentment with His will.

2 The foundation of wisdom is fear of God, exalted is His mention, dread of His might and chastisement, and awe before the manifestations of His justice and decree.

3 The essence of religion is acknowledgment of what has been revealed by God and adherence to the ordinances set forth in His unerring Book.

4 The foundation of dignity is for the servant to be content with what has been bestowed upon him and to be satisfied with what has been decreed for him.

5 The essence of love is for the servant to turn toward the Beloved and to turn away from all else, with no desire other than what his Lord wills.

6 The foundation of remembrance is steadfastness in the presence of the One remembered and forgetfulness of all else.

7 The essence of trust in God is for the servant to act and strive in this world, to rely upon God, and to look solely to the bounty of his Lord, for unto Him all matters of the servant return in the end.

8 The essence of detachment is turning toward God, entering His presence, fixing one’s gaze upon Him, and bearing witness before Him.

9 The foundation of innate nature is acknowledgment of one’s poverty before God and submission by one’s own choice before the Sovereign, the Mighty, the Omnipotent.

10 The essence of power and courage is to exalt the Word of God and to remain steadfast in His love.

11 The essence of beneficence is for the servant to manifest what God has bestowed upon him, and to give thanks to Him in all circumstances and at all times.

12 The essence of faith is to speak little and to act abundantly; and if one’s words exceed his deeds, know that his nonexistence is better than his existence, and his demise is better than his survival.

13 The foundation of well-being is silence, consideration of the consequences, and withdrawal from the people.

14 The essence of aspiration is for a person to spend on himself, his family, and the poor among his brethren in faith.

15 The essence of commerce is My love; through it, all things are enriched by all things, and without it, all things are impoverished by all things. This is what has been inscribed by a radiant finger of might.

16 The foundation of all evil is the servant’s heedlessness of his Lord and his attachment to others beside Him.

17 The foundation of the fire is denial of the signs of God, disputation with those sent by Him, rejection of them, and arrogance toward them.

18 The foundation of all knowledge is the recognition of God, exalted is His glory, which is attained only through the recognition of His Manifestation.

19 The essence of abasement is to leave the shadow of the Merciful and to enter the shadow of Satan.

20 The essence of disbelief is associating partners with God, relying on anything other than Him, and fleeing from His decrees.

21 The foundation of loss is for one’s days to pass without knowing himself.

22 The essence of all that We have mentioned to you is fairness, which is for the servant to free himself from delusion and imitation, to observe the manifestations of creation with the eye of oneness, and to perceive all things with a penetrating vision.

23 Thus have We taught you and set forth for you the words of wisdom, so that you may give thanks to your Lord within yourself and glory in them among the people of the world.

{{< pagebreak >}}
