# BH03535 {#sec-bh03535 .unnumbered}

Dawlatabad, His Excellency \`Alá' Allah.

To all who are on the earth, the call of the Book has come from Us to those who, by its lights, believe in Me. For the cry of the Most Merciful has reached the station of the upright, which is high and elevated, and He guides the heedless ones to the Hall of the Mighty, the Powerful. And I have revealed to you before what the breath of God has brought forth, so take heed. And after another shower comes down upon it, let the others declare whether this is from the servants of this painful mention. The people of the Promised One, the essence of the covenant, said: How long will you follow the rising points of the hearts, and comprehend that the forebears have arrived and the Greatest Veil is lifted in the name of the Ancient King, closely.

To this sea of God, the servant, the Seer. I complain to You from the lofty gaze that prevented the servants from the King of existence after He was created for this mention, the one who advanced the mentions. So ask God that the One Who is not seen after God, the Knower, the Grievous, may come to you. Indeed, I am the one who believes in God, the One, the Omnipotent, the Escaper, spreading likewise His command, pleasing to you from God, the Master of the Day of Return. Know that in our time, the servants’ affection has left its mark through the ruling of the Bayan, which appears on the earth, causing the lovers to tremble. What I mentioned is a silence from creation, and follow what was revealed in the Book, the color of the Lord of the people. Turn to it, for you and those who drank the cup of life in My days and soared with the wings of longing in My air and cut off from anything besides Me and were attracted by the sound of My pen and the Tablets, and the profits of My care and the best of what I mentioned. Behold, they are the stars of My mention among the horizons. So make them victorious.

{{< pagebreak >}}
