# BH03560 (The Next Manifestation) {#sec-bh03560 .unnumbered}

In the heavens and on earth, is there a path for my recognition that you may establish? Out of grace from Us upon the worlds, since the appearance of my previous manifestation is the proof of this Most Holy Manifestation. Therefore, from the heaven of Our will, We have revealed the verses and made them a proof for all in the heavens and the earth. And until this Manifestation, the verses alone have been a proof for all, for in all previous books, We have revealed this command. Although in this Manifestation, all the powerful verses, the swift proofs, the new signs, the elevated manifestations, and the divine attributes have appeared, all that is a grace from Us upon all creatures.

However, after the matter is in the hand of God, to establish the proof for the manifestations to come, He will reveal His command in different forms. We are the rulers of all affairs, and all matters are in the grasp of Our power; We do what We will and command what We desire. In this Manifestation, God, glorified be His mention, has willed that many of the sincere followers speak with the verses, and thus We have determined another proof for the next manifestation. So that none may become proud who brings the words upon God, the Mighty, the Powerful, the Capable, as he who, by Our permission, spoke with the words of those around Me, upon God who created, raised, and protected him. Thus, from three calamities, He preserved him under the wing of His bountiful grace. We have decreed in this night, and We decree with a command from Us, and We are able to do what We will and besides Me is My creation. O My creation, do not be proud.

{{< pagebreak >}}
