# BH06114 {#sec-bh06114 .unnumbered}

Write to His Excellency Mahdi: We have endowed the noble before, through Our voice, so that people may witness Our power and authority, then Our greatness and majesty. But My ignorant loved ones have taken him as a partner unto Me, causing corruption in the lands, and they have been among the corrupt. Observe how ignorant the souls are who are in Our presence, yet they have gone astray and spread such words. Say: He is a servant among My servants, whom We created by Our power, and We made him speak in praise of Me among the worlds. And if he deviates an instant from My command, he will surely be obliterated. Say: Nothing but My command has created him and his likes. Allah has grown them from this tree. They are the clouds of mercy, the rains of bounty, the lamps of guidance, and My guides among creation, to be steadfast in My command. And indeed, your Lord has not taken unto Himself a partner, nor a likeness, nor a minister, nor a peer, nor an equal, nor a successor.

{{< pagebreak >}}
