# BH07562 {#sec-bh07562 .unnumbered}

In the Name of the All-Bountiful, the All-Powerful

The flourishing of God's Cause has always been and continues to be the nurturing of His servants. The Most Exalted Pen has enjoined all to the upbringing of children and youth. Consider the trees: before they are grafted, their fruits are not worth mentioning, but afterward, that which is worthy of praise becomes manifest. A tree, being part of the plant kingdom, through even a slight nurturing, attains to such a station. Now, reflect upon the trees of human existence: if they receive the nurturing of the True Educator, they will turn their attention to the welfare of the world.

O Hasan! You have been mentioned by this wronged one and have attained this most exalted, most sacred Tablet. Give thanks to the purpose of the world, who has supported you and made you aware of the dawning rays of the Day of Revelation. Say: "Praise be to You, O my God, for guiding me and enabling me to recognize You. Verily, You are the One whom nothing can hinder, and no matter can prevent. In Your grasp are the reins of all affairs; You grant and You withhold. Indeed, You are the Almighty, the All-Powerful."

{{< pagebreak >}}
