# BH08181 {#sec-bh08181 .unnumbered}

"The Presence of the Greatest Branch is God."

1 Two pages arrived on Wednesday. Each letter of them testified to the unity of the Essence and the sanctification of the Self of Truth from night, and like joy to your pen, your ink, and the paper, triumphant in your remembrance.

2 We ask God to enter with you into His servants, in the tumult of the sea of His oneness, and to quench them with your remembrance as the Kawthar of life, and with your exposition as the nectar of gnosis. \[We ask God\] to fortify you with the armies of knowledge and wisdom, so that through you He may open the cities of horizons and hearts. There is no god but He, the Mighty, the Generous.

3 O my vision, upon you be My glory, and the sea of My grace, and the sun of My bounty, and the sky of My mercy. We ask God to illuminate the world with your knowledge and wisdom and to decree for you that which brings joy to your heart and gratification to your eye. Indeed, He is Powerful over all things. Glory, mercy, and praise be upon you and upon those who circulate around you.
