# BH09144 {#sec-bh09144 .unnumbered}

O My Greatest Branch!

Your book has reached this wronged one, and We have heard what you have expressed to God, the Lord of all worlds. We have made you a shield for all of creation, a protection for those in the heavens and on the earth, and a stronghold for those who believe in God, the Singular, the All-Knowing.

We ask God to protect them through you, to enrich them through you, to provide for them through you, and to inspire you with that which will be the source of wealth for the people of creation, the ocean of generosity for those in the world, and the dawn of grace upon the nations. Indeed, He is the All-Powerful, the All-Knowing, the Wise. We ask Him to water the earth and everything upon it through you, so that it may produce the pasture of wisdom and eloquence, and the grains of knowledge and understanding. Indeed, He is the Guardian of those who turn to Him, the Helper of those who call upon Him. There is no God but Him, the Mighty, the Praiseworthy.

{{< pagebreak >}}
