# BH09086 {#sec-bh09086 .unnumbered}

O my God! This is a branch that has grown from the tree of Your oneness and the Lote Tree of Your uniqueness. You see, O my God, that he gazes toward You and clings to the cord of Your grace. So, protect him in the shelter of Your mercy. You know, O my God, that I desire nothing for him except what You desire, and I have chosen him only as You have chosen him. Therefore, assist him with the hosts of Your earth and Your heaven, and support, O my God, those who support him. Then, choose those whom he chooses and strengthen those who turn toward him. Then, reject those who deny him and do not seek him.

O Lord, You see that as the revelation descends, my pen moves and my limbs tremble. I beseech You, by my love for You and my longing to manifest Your Cause, that You decree for him and for his loved ones what You have decreed for Your messengers and the trustees of Your revelation. Verily, You are God, the All-Powerful, the Almighty.

{{< pagebreak >}}
