# Kitab-i-Ahdi (The Book of My Covenant) {#sec-kitab-i-ahd .unnumbered}

1 The higher horizon may be devoid of the trinkets of this world, yet we have laid within the treasuries of trust and resignation, an incomparable treasure for the inheritors of a desired and peerless heritage. We have not assigned any treasure to be sought nor have we added to their burdens. Hidden within the wealth is fear and concealed danger. Contemplate, then remember what the All-Merciful has revealed in the Discrimination, "Woe to every slanderer and backbiter, who has gathered wealth and counted it." The wealth of the world does not warrant attention. What is subject to extinction and change is not worthy of attention, except to a known extent.

## Purpose of Baha'u'llah's Ministry

2 The purpose of this oppressed one in enduring hardships and tribulations, in revealing verses and showing clear proofs, has been to extinguish the fire of hatred and animosity so that, hopefully, the horizons of the hearts of the people of the world may be illuminated with the light of concord, and achieve true peace. This radiant statement has to emanate from the divine tablet. All should look towards it. O people of the world, I exhort you to that which will cause your ranks to be elevated: hold fast to the fear of God and attach yourselves with the cord of righteousness. Truly, I say, the tongue is for mentioning what is good; defile it not with unseemly talk. God has forgiven what is past. Hereafter everyone should utter what is meet and seemly, and refrain from slander, abuse and whatever causes sadness in people. The station of man is high. A short while ago this exalted word flowed from the treasury of the pen of glory: "The station of man is great, very great." What has been hidden within man is today being revealed and will be so in the future. The station of man is high, if he holds to truth and uprightness, and remains firm and steadfast in the Cause. In man the merciful One has placed the greatest of all trusts. To him the "sun" and "moon" of eyes, ears, and faculties of human perception have been subjected. The "stars" of his divine attributes shine out from him, and his light is indeed a light which finds its source within God. His station is lofty, and his signs illuminating. He is indeed the highest, the noblest of all beings.

3 Every seeker today has found his robe, and with a pure heart has turned towards the highest horizon. He is mentioned in the Crimson Scroll among the people of Bahá. Take a cup of favor from My name, then drink from it in remembrance of Me, the Mighty, the Wondrous.

## To the People of the World

4 O people of the world, the Divine religion is for love and unity. Do not make it a cause of enmity and discord. To the discerning ones and the people of insight, that which is the cause of preservation, and the reason for comfort and tranquillity of the servants, has been revealed from the Most High Pen. However, the ignorant of the earth, being educators of self and desire, are heedless of the mature wisdom of the True Wise One and act and speak according to assumptions and illusions.

## To the Friends of God and His Trustees

5 O Friends of God and His trustees, the kings are manifestations of power, the dawns of glory, and the wealth of the truth. Pray for them that the dominion of the earth might be granted to those souls and that they might establish their hearts for themselves.

6 Conflict and contention are strictly forbidden in this Book. This is the command of God in this greatest revelation, He protected it from the fate of obliteration and adorned it with the pattern of affirmation. Indeed, He is the All-Knowing, the Wise.

## To the Manifestations of Command

7 The manifestations of command and the revealers of decree, adorned with the pattern of justice and fairness, are necessary for all those souls. Blessed are the leaders and the learned in Baha. They are my trusted ones among my servants, the dawning places of my ordinances among my creation. Upon them is my glory, my mercy, and my bounty which encompass existence. In the Most Holy Book, at this station, what is revealed are the illuminating and shining lights of Divine forgiveness emanating from the horizons of His Words.

## To Baha'u'llah's Branches, Twigs, and Kindred

8 O my branches in existence, a mighty power and a perfect strength are hidden and concealed in Him. Look towards Him for unity, not with the apparent differences from Him.

9 The Will of God is that the branches, twigs, and affiliates should look in alignment with the Greatest Branch. Look at what We have revealed in Our Most Holy Book. When the sea of reunion rages and the book of the beginning is fulfilled in the end, turn towards Him Whom God Will, who has branched out from this Ancient Root. The intended meaning of this blessed verse has been the Greatest Branch. Thus We have made the matter apparent as a favor from Us, and We are the Gracious, the Generous. God has decreed the station of the Greater Branch after His station. He indeed is the wise commander. We have chosen the Greater after the Greatest, a matter from the knowledgeable and informed.

10 The love for the branches is necessary for everyone, but what Allah has truly allocated for them in the wealth of the people...

11 "O my branches, twigs, and kindred! I enjoin you to fear God, to do good, to do what is fitting, and to elevate your stations. Indeed, I say, piety is the greatest commander for the support of the divine cause, and the troops befitting this commander are virtuous, pure, and pleasing deeds and manners."

## To The People of Baha

12 "Say, O my servants, do not make the causes of order a source of disorder, and do not make the reasons for unity a reason for discord. It is hoped that the people of Bahá will regard the blessed statement, 'All are from God,' and this sublime word will act like water to extinguish the flames of resentment and hatred hidden in hearts and breasts. Various parties will find true unity through this one word. Indeed, He speaks the truth and guides to the path, and He is the Powerful, the Mighty, the Beautiful."

13 "Respect and consideration for the branches is necessary for all, for the exaltation of the Cause and the elevation of the Word, and this decree is mentioned and recorded in the divine books before and after. Blessed is the one who succeeds in what he is commanded to do by the Ancient Commander. Similarly, respect for the sanctity of the House of God, the branches, the descendants, and the followers is enjoined. I advise you to serve the nations and improve the world."

14 "From the celestial realm of utterance, descended that which is the cause of the life of the world and the salvation of nations. Listen with true attention to the exhortations of the Supreme Pen. Indeed, they are better for you than what is on the earth. The glorious, the wondrous Book bears witness to this."

{{< pagebreak >}}
