# **Lawh-i-Bisarat (The Tablet of Glad-Tidings)** {#sec-lawh-i-bisarat .unnumbered}

This is the call of the Most Glorious that rose from the highest horizon in the prison of Akka.

He is the Manifest, the All-Knowing, the Informed.

The Truth is witness and the manifestations of His names and attributes bear testimony that the purpose of the elevation of this Call, and the exalted word, is that the fountain of speech may be purged from idle fables, and become prepared for the reception of the exalted, blessed word that has been revealed from the treasury of the knowledge of the Creator of heaven and names. Blessed are the just ones, O people of the earth.

## The First Glad-Tidings

Which was revealed from the Mother Book upon all the peoples of the world, is the abolition of the decree of holy war from the Exalted, Noble Book. This is the Book by which the gate of grace has been opened before all who are in the heavens and on the earth.

## The Second Glad-Tidings

Permission has been granted for the peoples of the world to associate with each other with spirit and fragrance. O people, associate with all religions in spirit and fragrance. Thus has the light of permission and desire shone from the horizon of the command of God, the Lord of the worlds.

## The Third Glad-Tidings

The teaching of various languages is decreed by the Most High Pen. The kings, whom God strengthens, or the ministers of the earth are to consult, and to adopt one of the existing languages, or to establish a new one, and to teach this to children in all the schools of the world. Also, they should adopt a universal script, so that the entire earth may be considered as one. Blessed is he who hears the call and acts in accordance with what God, the Lord of the great Throne, commands.

## The Fourth Glad-Tidings

Each of the kings, may God grant them success, is to rise and help this oppressed group. They all should strive to surpass each other in love and service to them. This decree is obligatory for everyone. Blessed are those who act accordingly.

## The Fifth Glad-Tidings

6 This group, residing in any country, should behave with trust, honesty, and purity towards that government. This is what has been revealed from the ancient Commander upon the people of the world. It is mandatory and necessary to assist this most significant matter, which has descended from the heavens of the will of the sovereign Lord. May the fire of hatred, kindled in the hearts of some groups, be extinguished by the water of divine wisdom and godly admonitions, illuminating and brightening the horizons with the light of unity and concord. Hopefully, with the attention of the manifestations of the power of Truth, the world's armaments will be converted into instruments of reform, and corruption and strife will be eliminated from among the servants.

## The Sixth Glad-Tidings

The Most Great Peace is that whose description has been revealed from the Pen of the Most High. A bounty for those who adhere to it and act in accordance with what has been commanded by God, the All-Knowing, the Wise.

## The Seventh Glad-Tidings

The choice of clothing and the cut of the beard and its dressing are left to the discretion of men. But beware, O people, lest ye make yourselves the playthings of the ignorant.

## The Eighth Glad-Tidings

The deeds of the monks and priests of the religion of the Spirit of God (Jesus), upon whom be God's peace, and His glory with God, are remembered. However, today they should come out of their seclusion and engage in what benefits them and benefits the servants. We have allowed everyone to marry, so that from among them may arise those who remember God, the Lord of all that is seen and unseen, and the Lord of the lofty throne.

## The Ninth Glad-Tidings

The transgressor, in a state when they find themselves free from all else but God, should beg for forgiveness and mercy. To admit one's wrongs and transgressions in the presence of others is not permissible, as it neither was nor is the cause and means of divine forgiveness and pardon. Moreover, this confession before people is the cause of humiliation and disgrace, and God, may His glory be exalted, does not love the humiliation of His servants. Indeed, He is the considerate, the generous.

The sinner should seek mercy from the ocean of divine mercy between themselves and God, ask for forgiveness from the heavens of bounty, and present the following plea:

> "Oh my God! My God! I beg You by the blood of Your lovers, whom Your sweet utterance attracted and caused them to ascend to the high apex, the position of the great martyrdom, and by the hidden mysteries in Your knowledge, and by the enshrined pearls in the sea of Your bounty, to forgive me, my father, and my mother. You are the most merciful of the merciful. There is no god but You, the Forgiving, the Generous.
>
> Oh my Lord! You see the essence of sin turning towards the sea of Your gifts, the weak towards the sovereignty of Your power, and the poor towards the sun of Your wealth. Oh my Lord, do not disappoint him with Your generosity and kindness, do not prevent him from the outpourings of Your days, and do not drive him away from Your door which You have opened for everyone on Your earth and in Your heavens.
>
> Alas, alas, my sins have prevented me from drawing near to Your sanctified court, and my offenses have distanced me from turning towards the secrets of Your glory. I have done what You forbade me to do and I have neglected what You commanded me to do. I ask You, by the power of Your names, to write for me from the pen of Your grace and gifts what will bring me closer to You and purify me from my offenses that have come between me and Your pardon and forgiveness. Indeed, You are the Capable, the Overflowing. There is no god but You, the Mighty, the Gracious."

## The Tenth Glad-Tidings

We have lifted the commandment to erase the Holy Books and Tablets, as a favor from God, the Proclaimer of this Great Announcement.

## The Eleventh Glad-Tidings

The acquisition of all kinds of knowledge and arts is permissible, yet it is the beneficial sciences that aid the progress of humanity which are particularly endorsed. Thus is the decree from a wise and discerning Authority.

## The Twelfth Glad-Tidings

Each one of you is obligated to engage in a vocation, such as crafts, agriculture, and the like. We have deemed your engagement in such work as equivalent to the worship of God, the True One. Reflect, O people, on the mercy of God and His affections. Then express gratitude to Him in the evening and in the morning. Do not waste your time in idleness and sloth, but engage in that which profits yourselves and others. Thus is the decree given in this Tablet from which the Sun of Wisdom and Explanation has shone. The most despised of men in the sight of God are they who sit and beg. Hold fast to the rope of means, placing your trust in God, the Provider of all means. Every soul should be occupied in some form of occupation or craft, and this very act is considered worship in the sight of God. Indeed, this is from His immense, immeasurable bounty.

## The Thirteenth Glad-Tidings {#sec-the-thirteenth-good-news .unnumbered}

The men of God's House of Justice have been charged with the affairs of the people. They, in truth, are the Trustees of God among His servants and the daysprings of authority in His countries.

O people of God! That which traineth the world is Justice, for it is upheld by two pillars, reward and punishment. These two pillars are the sources of life to the world. Inasmuch as for each day there is a new problem and for every problem an expedient solution, such affairs should be referred to the Ministers of the House of Justice that they may act according to the needs and requirements of the time. They that, for the sake of God, arise to serve His Cause, are the recipients of divine inspiration from the unseen Kingdom. It is incumbent upon all to be obedient unto them. All matters of State should be referred to the House of Justice, but acts of worship must be observed according to that which God hath revealed in His Book.

O people of Bahá! Ye are the dawning-places of the love of God and the daysprings of His loving-kindness. Defile not your tongues with the cursing and reviling of any soul, and guard your eyes against that which is not seemly. Set forth that which ye possess. If it be favorably received, your end is attained; if not, to protest is vain. Leave that soul to himself and turn unto the Lord, the Protector, the Self-Subsisting. Be not the cause of grief, much less of discord and strife. The hope is cherished that ye may obtain true education in the shelter of the tree of His tender mercies and act in accordance with that which God desireth. Ye are all the leaves of one tree and the drops of one ocean.

## The Fourteenth Glad-Tidings

It is not necessary to undertake special journeys to visit the graves of the departed. If the expenses of such journeys are at the disposal of the affluent, it is better for them to spend it for the establishment of the House of Justice which would be pleasing and acceptable in the sight of God. Blissful are those who observe this.

## The Fifteenth Glad-Tidings

Although a republican form of government profits all the peoples of the world, yet the majesty of kingship is one of the signs of God. We do not wish that the countries of the world should remain deprived thereof. If the sagacious combine the two forms into one, great will be their reward in the presence of God.

In former religions such ordinances as holy war, destruction of books, the ban on association and companionship with other peoples or on reading certain books had been laid down and affirmed according to the exigencies of the time; however, in this mighty Revelation, in this momentous Announcement, the manifold bestowals and favours of God have overshadowed all men, and from the horizon of the Will of the Ever-Abiding God, His infallible decree hath prescribed that which We have set forth above.

We yield praise unto God---hallowed and glorified be He---for whatsoever He hath graciously revealed in this blessed, this glorious and incomparable Day. Verily, if everyone on earth were endowed with a myriad tongues and were to continually praise God and extol His greatness from now until a time that knoweth no end, yet would His loftiness and grandeur remain unappreciated and His praise unsung. He verily is the All-Knowing, the All-Wise, the All-Seeing, the All-Informed.

We pray unto God to graciously aid the manifestations of affluence and power---the kings and rulers of the earth---for they are His trustees, who should strive to administer His realms as they would administer His own affairs. Verily, He is the potent, the exalted, the protecting, the self-subsisting.

{{< pagebreak >}}
