---
title: "Lawh-i-Khalil"
subtitle: "Tablet to Khalil"
editor: visual
---

1 He is Allah, the King, the Sovereign, the Mighty, the Powerful, the Self-Subsisting.

2 These are the verses of Allah, the Protector, the Self-Sustaining, to those who have believed in Allah and His signs, and they are safe from associating others with Him. Say, O people, why do you deny me when you bear witness that I have brought you the signs which cause the hearts of the believers to melt and stupefy the minds? O people, have you forgotten the judgment of Allah as revealed in the Bayan from the beloved Mighty One? And He has taken a covenant from you in every book, indeed in every published parchment, that you will not argue about the signs of Allah when they are revealed with truth, and you will not argue with him who brings you the Tablets of the beloved Mighty One. Even if you don't believe in him, do not oppose him. Fear Allah, then His beauty, do not disbelieve.

Indeed, we revealed before to Muhammad, the Messenger of Allah, if you understand, no one argues about the signs of Allah except those who disbelieve. Likewise, it was revealed before from Allah, the Protector, the Self-Sustaining. Say, O people, fear Allah and do not be arrogant towards him who fears His overwhelming power. Beware, do not invalidate your deeds, and do not cling to what you have, but to what has been revealed with truth from the Mighty, Self-Sustaining. Sanctify yourself, then remind the servants of what the Spirit has inspired in you, and do not fear anyone or grieve for the calamities and harm that befall you. Rely on Allah, your Lord, and do not be among those who do not reflect on the signs of Allah.

By Allah, if you stand firm for the love of Allah and His servant, Allah will support you against all on earth. Indeed, there is no god but He; He supports whom He wills by saying 'Be', and it is. Thus, we recite to you from the signs of Allah and cast into your hearts, and the hearts of those who will only look with a greater look, what will reassure you in this hidden, precious beauty. Indeed, you have broken the veils of illusion, then emerged from behind the clouds with a force from Us, and a power from Our presence, to witness what none of the creation has witnessed. This is what We have testified to you with truth in this sacred, praiseworthy station. Beware not to be like those who follow nothing but their desires, and they wander in the valley of delusion.

## People Were Created According to the Nature of Allah

3 As for what you asked about the nature (Fitra), know that people were created according to the nature of Allah, the Protector, the Self-Sustaining. He determined the decrees of the matter for every soul as it is inscribed in the preserved Tablets of the Mighty. However, this is manifested through your own will, as you bear witness in your actions. Look, for example, at what is forbidden for the servants in the Book, as you look at the Bayan (clear explanation) where Allah has permitted what He willed by His command and forbidden what He willed by His authority. Say, all of this is in the Book, do you not bear witness? But people, after their knowledge of what they were forbidden, commit it. Is this attributed to Allah or to themselves, if you are just? Say, every good deed is from Allah, and every evil deed is from yourselves, do you not recognize this? This is what is revealed in all the Tablets, if you know. Indeed, He knows your actions before they appear as He knows after they appear. Indeed, there is no god but He; to Him belongs the creation and the command, and everything with Him is in the holy concealed Tablets.

This knowledge was not the cause of action in His creation, just as your knowledge of something was not the cause of its appearance in what you intended if you intended and knew, or you learn. Thus, we cast upon you the signs of innovation and turn them with truth, perhaps people were certain of the signs of their Lord. Then reflect upon yourself in what you asked, perhaps Allah will open the doors of knowledge and wisdom upon your heart, and He will make you witness the creation of everything and acquaint you with the secrets of what was and what will be. By Allah, all of that is with Him, and He is the easiest over everything. He gives whom He wills from His creation by a command from Him, and indeed He is the Mighty, the Beloved.

And you are a bird in the holy expanse, in this air in which the breezes of the Living One move. Beware of being from the people of stagnation, strive within yourself to ascend at every moment to another sky and another expanse, to glimpse at every instant the secrets of concealed innovations, because there was no end to its bounty for the sky, and no beginning for its bounty on earth to be accomplished with the foot or the wing or the mind and comprehension. Break the veils with my beloved Mighty name, and do not look back at anyone but Allah, your Lord. Turn towards my precious witnessed face, so the grandeur of the turbans will not prevent you from entering the sanctuary of Allah, the Protector, the Mighty, the Holy. For we have found the filling of the Bayan to be like the filling of the Furqan, a stronger veil, if you know. They say the same as what they said and do the same as what the previous nations did.

So, you will know. Strive in yourself so you do not walk in their footsteps, but in the footsteps of Allah, your Lord, on this blessed, extended, illuminated path. If asked about them, what is the difference between you and them? They would say what they do not perceive. Thus, their souls were adorned, and their hearts were torn with what they were about to earn.

## People Know According to Their Levels, Not According To What Was Destined For Them

4 As for what you asked about me, know that I am a servant who believes in Allah, His signs, His messengers, His books, and we do not differentiate between any of them. Thus, I was commanded by Allah, the Protector, the Sustainer, and I believe in everything that came down from Him and what descends then from the beloved sacred sky. I follow what I was commanded in the book by the power and strength of Allah and I would not like to deviate from a single letter of it. My existence, my being, and then my tongue bear witness to that if you bear witness. I make lawful for myself everything that Allah has made lawful in the statement, and I forbid what is forbidden by Him, and I believe in everything that came down in it if you believe.

Indeed, those who make lawful what Allah has forbidden them, and they forbid what Allah has made lawful in the book, those do not understand anything and they do not know. But this question should not be asked by anyone because this status will not be moved by the pen and ink will not flow on it if you know. And if this question was from someone other than you, we would not answer it with a single letter. But when we wanted a matter from the matters for you, that's why we answered you, perhaps you will correct yourself and be among those who are guided in these days that have taken every soul's intoxication and all who were turning away from its beauty.

Except for those who cut off everything from everything they heard and they were witnessing then looking in the holy eye by Allah. I was asked about the status of the one who was greater than the creation of the heavens and the earth, and Allah made him above the testimonies of His servants and none but the knowledgeable will understand it. Indeed, people know according to their levels and measures, not according to what was destined for him, so exalted be He, exalted be He from what you ask.

And if you remove the veil from your sight and ascend to the holy air in this air that blows in this sky and cut off from everyone in the heavens and the earth and from every limited matter to cast the spirit in your chest from this position that enriches you from everything that was created and is created and is enough for you from everything as it was and as it will be, thus the pen of the matter reads to you about the wisdom of Allah, the Protector, the Sustainer, and casts upon you what brings you closer to the glorious praiseworthy status, which most of the servants were prevented from entering. And no one will reach it except those who were on the eternal beds, they are reclining.

## About My Son (Mirza Muhammad Ali), and the Status of Baha'u'llah's Sons

5 As for what you asked about my son, know that if my sons follow God's laws and do not exceed what has been specified in God's book, the prevailing, the Ever-Existing, and they command themselves and the servants to do good, and they forbid evil, and they testify to what God has testified in His decisive verses, the conclusive, the definitive, and they believe in whoever God reveals on the day in which the times of the former and the latter are counted, and on it, everyone presents themselves to their Lord, and they will not disagree on God's command and will not stray from His ordained, written law. Then know that they are leaves of the tree of monotheism and its fruits, and with them, the clouds rain and the clouds lift with grace if you truly believe. They are God's household among you and His family in your midst, and His mercy upon the worlds if you know. From them, the breeze of God blows on you, and the winds of dignity and love pass over those close. They are God's pen, His command, and His word among His creatures, and with them, He takes and gives if you understand. Through them, the earth has shone with the light of your Lord, and the signs of His grace have appeared to those who do not deny God's signs. However, those who hurt them have hurt me, and those who hurt me have deviated from God's path, the prevailing, the Ever-Existing. So, you will find the deviation of the deviators and their arrogance towards us and their transgression against ourselves without clear evidence or a preserved book.

Say, O people, they are God's signs among you, beware of arguing with them, or killing them, or be among those who oppress and do not realize. They are God's secret on earth and returned under the hands of the oppressors on this earth that fell behind the elevated mountains. All of that was returned to them at the time when they were young in the kingdom, and they had no sin but in the path of God, the Capable, the Powerful, the Mighty, the Beloved, and those from them who appear naturally and God runs from their tongues signs of His power, and he is among those God has chosen for His command. There is no god but He, to Him belongs creation and command, and we are all commanded by His command. We ask God to make them successful in obeying Him and to provide them with what pleases their hearts and the hearts of those who inherit Paradise from God, the Mighty, the Prevailing, the Ever-Existing.

So we have bestowed upon you in this tablet and revealed to you what was hidden from you, a favor from us to you and to those who are guided by God's guidance in this dawn, they are guided, and indeed, you are. So guard this tablet as your eyes, beware not to reveal to anyone but its people. This is God's command to you with what is hidden and do not exceed what you have been commanded because we found that the full explanation is most concealed from the earth's religions except for what your Lord wills, and so we have counted the command if you count. We ask God to make them successful in His command so that they can pierce the veils and emerge from behind the praises with authority from God, the Capable, the Holy. Then know that we answered your questions at the time when your book came before us with a clear Persian tongue, and when we found no messenger to send to you, we erased it in the sea by our command lest it raise the clamor of the polytheists. And in his hand is the dominion of everything, he erases what he wills and confirms, and with him are sacred tablets, the preserver. Then we answered you in three of them with a wonderful Arabic tongue and we held the pen from the two for wisdom that no one should know but God, your Lord, and the Lord of the worlds, and we run the pen in its time when the command comes from a protected holy horizon if God wills and wants. Indeed, there is no god but He, He judges what He wills and reveals what He wants. All the spirit, glorification, and perpetuity to you if you are firm in the command of your Lord.

{{< pagebreak >}}
