# Lawh-i-Ard-i-B치 (Tablet of the Land of B치) {#sec-lawh-i-ard-i-b치 .unnumbered}

He is God, exalted is His state, the Greatness and the Power.

1 Praise be to the One Whose land of B치 was honored by the arrival of Him around Whom all names have revolved. Through this, the atoms and all possibilities rejoiced for what has risen, shone, appeared, and emanated from the prison's gate. This is where the sun of the beauty of the Greatest Branch of God, the ancient and most firm Secret of God, emerged, heading towards another place. By this, the land of the prison was saddened, and another rejoiced.

2 Exalted, exalted is our Lord, the Creator of the heavens and the Maker of all things, who by His authority opened the prison gate to reveal what He had previously sent down in the tablets. Indeed, He is the Almighty over what He wills, and in His grasp is the dominion of creation. He is the Almighty, the All-Knowing, the Wise.

3 Blessed, then blessed be the land that was graced by His arrival, the eye that found solace in His beauty, the ear that was honored by hearing His call, the heart that tasted the sweetness of His love, the breast that expanded with His remembrance, the pen that moved in His praise, and the tablet that bore His traces.

4 We ask God, blessed and exalted, to honor us with meeting Him soon. Indeed, He is the Hearing, the Powerful, the Responsive.

{{< pagebreak >}}
