# Lawh-i-Tibb (Tablet of Medicine) {#sec-lawh-i-tibb .unnumbered}

1\) Indeed, bestowed upon one of the physicians is the splendor of God.

He is God, the All-Knowing.

The tongue of antiquity speaks of what becomes abundant in the hearts when the physicians are absent.

2\) Say, O people, eat not except when hungry, and drink not until after you feel a need. Excellent is the practice in the open air, by it the limbs are strengthened, and when overfull, it is a dark calamity. Do not forsake treatment when needed and leave it when the temperament is balanced. Approach food only after digestion, and swallow only after thorough chewing. Treat an ailment first with foods and do not proceed to medicines. If what you desired from simple remedies suffices, do not switch to compounds. Abandon medicine when healthy and take it when needed. When opposites meet at the table, mix them not; be content with one of them. Begin first with the soft before the hard, and the liquid before the solid. Introducing food upon food is a danger; be wary of it. And when you start eating, begin with My most glorious name, then conclude with the name of your Lord, the owner of the throne and the dust. If you eat, walk a little for the food to settle, and what is hard to chew, avoid it as advised by the wise. Thus commands you the Supreme Pen. Eating a little in the morning is indeed a lamp for the body, and abandon harmful habits, for they are a calamity for creatures.

Confront diseases with their causes, and this statement in this matter is the decisive word: always embrace contentment in all situations, by it the soul is saved from laziness and ill condition. Avoid sorrow and grief; by them great afflictions occur. Say envy consumes the body and anger burns the liver; avoid both as you would avoid a lion. Purging superfluities is the mainstay but do so in moderate seasons, and one who exceeds in his eating aggravates his illness. We have decreed a cause for everything and given it an effect; all that is from the manifestation of My influencing name over things, indeed, your Lord is the ruler over what He wishes. Say, by what we have explained, the mixing does not exceed moderation, nor do its quantities exceed conditions. The essence remains in its purity. And the sixth and a sixth of the sixth remain in their state. Both the active and the passive are safe, and upon God, we rely. There is no god but He, the Healer, the All-Knowing, the Helper. What the Supreme Pen has run on such words is but for My love for you to know that worry has not taken the beauty of the ancients nor has it grieved over what has come upon them from the nations. And grief is for those who miss something, but nothing escapes from His grasp who holds all in the heavens and the earth.

3\) O physician, first heal the sick with the remembrance of your Lord, the owner of the Day of Calling. Then with what We have decreed for the health of temperaments. By my life, the physician who has drunk the wine of My love, his meeting is healing, his spirit mercy and hope. Say, hold to it for the balance of temperament, for it is supported by God for healing. Say, this knowledge is the noblest of all sciences, for it is the greatest cause from God, the reviver of the remains to preserve the bodies of nations, and place it above all sciences and judgments, but today is the day when you stand for My support, cut off from the worlds.

## A Healing Prayer

4\) Say, O my God, Your name is my healing. Your remembrance my medicine. Your proximity my hope. Your love my comfort. Your mercy my physician and my aid in this world and the next. And indeed, You are the Giver, the All-Knowing, the Wise.

### Wisdom, Explanation, and Constancy

5\) All those whom I love are magnified by God. Say, today two matters are beloved and desired. One is wisdom and explanation. The other is constancy upon the order of your Lord, the Merciful. Every soul that succeeds in these two matters is considered and mentioned by God as from the people of the enduring city because these two orders are established and will be established among the servants if there is no wisdom and explanation, all will be afflicted. In this case, no soul would remain to guide people according to the unique law. And if there is no constancy, the mindful soul will not be effective.

Say, O friends, fear and anxiety are the demeanor of women, and if the divine loved ones overall consider, the visible conflicts in it should not frighten them from the power of those who oppress, and they should fly with the wings of longing to the light of the horizons. This servant has desired for himself what I have desired for all my friends. And this is by the command and preservation of the matter and is meant that the rememberers remain in the land to be occupied with the remembrance of the Lord of the worlds. Therefore, it is necessary and obligatory for all to preserve their own and their brothers' lives for the sake of God's command. And if the loved ones were to act according to what they are commanded, most people on Earth would be adorned with the garment of faith. Blessed is the soul that leads another soul to the enduring law and guides to eternal life. This is among the greatest deeds in the sight of your Lord, the Noble, the Exalted. And may the spirit and glory be upon you.
