# Salat-al-Mayyit (Prayer for the Dead) {#sec-salat-al-mayyit .unnumbered}

## For Males

In the prayer for the deceased, the following is recited during the Qunut:

O my God, this is Your servant and the son of Your servant who has believed in You and Your signs, and has turned towards You, detached from all else but You. You are indeed the Most Merciful of the merciful. I beseech You, O Forgiver of sins and Concealer of faults, to deal with him in accordance with Your heavenly grace and ocean of bounty, and to admit him into the shelter of Your supreme mercy, which has preceded the earth and the heavens. There is no God but You, the Forgiving, the Generous.

1.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, worship God" (إِنَّا كُلٌّ للهِ عَابِدُونَ) 19 times.

2.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, bow down to God" (إِنَّا كُلٌّ للهِ سَاجِدُونَ) 19 times.

3.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, are devoted to God" (إِنَّا كُلٌّ للهِ قَانِتُونَ) 19 times.

4.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, remember God" (إِنَّا كُلٌّ للهِ ذَاكِرُونَ) 19 times.

5.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, are grateful to God" (إِنَّا كُلٌّ للهِ شَاكِرُونَ) 19 times.

6.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, are patient for God" (إِنَّا كُلٌّ للهِ صَابِرُونَ) 19 times.

## For Females

In the prayer for the deceased (for females), the following is recited during the Qunut:

O my God, this is Your maidservant and the daughter of Your maidservant who has believed in You and Your signs, and has turned towards You, detached from all else but You. You are indeed the Most Merciful of the merciful. I beseech You, O Forgiver of sins and Concealer of faults, to deal with her in accordance with Your heavenly grace and ocean of bounty, and to admit her into the shelter of Your supreme mercy, which has preceded the earth and the heavens. There is no God but You, the Forgiving, the Generous.

1.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, worship God" (إِنَّا كُلٌّ للهِ عَابِدُونَ) 19 times.

2.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, bow down to God" (إِنَّا كُلٌّ للهِ سَاجِدُونَ) 19 times.

3.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, are devoted to God" (إِنَّا كُلٌّ للهِ قَانِتُونَ) 19 times.

4.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, remember God" (إِنَّا كُلٌّ للهِ ذَاكِرُونَ) 19 times.

5.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, are grateful to God" (إِنَّا كُلٌّ للهِ شَاكِرُونَ) 19 times.

6.  Then, recite once: "Allah-u-Abha" (اللهُ أَبْهَى), and say: "We all, verily, are patient for God" (إِنَّا كُلٌّ للهِ صَابِرُونَ) 19 times.
