# Suriy-i-Bayan (The Chapter of Clarity) {#sec-suriy-i-bayan .unnumbered}

1 This is the Surah of clarity that has been revealed by the Almighty Rahman to the one who believed in Allah and was among the guided ones, written in the tablets.

2 Mention the name of your Lord, the servant, when he entered the place of Paradise, the abode of the one upon whom the lights of the face shone from the east of beauty with clear signs. He stood facing the throne, witnessing Allah, the Most High, the Supreme, and heard the melodies of his Lord, the Most Merciful, the Most Compassionate, and attained all goodness when the breezes of holiness blew upon him with the satisfaction of Allah, the Most High, the Almighty, the Mighty, the Great.

3 O beauty of the foot, announce to the one who was standing before the throne what was destined for him in the holy records of the guardian \* Say that your arrival on the shores of greatness is the position in which the sea of names surges in the name of Allah, the Exalted, the Highest, for the betterment of what is created between the heavens and earth.

## To the Traveler to Allah

4 O traveler to Allah, take your share of this sea and do not deprive yourself of what has been decreed therein, and be among the winners. If all those in the heavens and the earth were granted a drop of it, they would be rich in their souls with the wealth of Allah, the Mighty, the Wise. Take, by the hand of separation, a chamber from this living sea, and then let your creatures be purified from human limitations and be brought closer to the view of Allah, the Greater, this Holy, Illuminating Sanctuary. If you find yourself alone, do not be sad, but seek solace in your Lord and be grateful. Convey the command of your Master to all those in the heavens and the earth, and if you find them receptive, show them the wisdom of Allah, your Lord, in the spirit which He has given you, and be one of those who turn toward Him. If you find them resistant, then turn away from them, rely on Allah, your Lord, and the Lord of the Worlds. By the truth of Allah, those who open their lips today in the remembrance of the name of their Lord will have the armies of Revelation descend upon them from the east of the Wise and Wise Name, and the people of the high will descend upon them, and so did He decree in the Majesty of the Command from a mighty and wise one. For Allah, behind the curtains of holiness, are servants who will appear on earth and support this cause, and they will not fear anyone, even if all the creatures of the world fight against them together. These people stand between the heavens and the earth and remember Allah with their highest voices, calling people to the path of Allah, the Mighty and the Praised.

Follow these people and do not be afraid of anyone, and be one of those who are not saddened by the noise of the people in the path of their Creator and are not deterred by the blame of the blamers. Carry the Tablet of Allah and its traces to those who believe, and give them the glad tidings of the satisfaction of the Holy, and then warn the polytheists. Say, O people, by Allah, I have been brought to you from the side of the Throne with news from the Mighty, the High, the Exalted Allah. And in my hands is a proof from Allah, your Lord and the Lord of your ancestors, so judge it with the balance of truth and with the arguments of the Prophets and the Messengers among you. If you find it to be true from Allah, beware not to argue with it, invalidate your deeds, and become polytheists.Those are the verses of Allah, sent down with truth and by which He justified His command between His creation and raised the banners of sanctification between the heavens and the earth. Say, O Messenger, this is the Sealed Scripture, which has been inscribed by the finger of the Divine and concealed behind the veils of the unseen, and has been revealed by the grace of a Powerful, Ancient master. In it, We have determined the measures of the inhabitants of the heavens and the earth and the knowledge of the first and the last. Nothing will escape His knowledge, and nothing will overpower Him in what He has created and will create, if you are among those who know. Say, the second orb has come, and We have extended the hand of power over all those in the heavens and on the earth, and We have revealed the greater secret of Our truth, a secret smaller than the consequences of the count. When the torrents die at the emergence of this red light on the spot of Sinai, so comes the beauty of the Merciful in the shades of the proof, and the matter is decreed by the Mighty and the Wise God.

## Convey These Messages To the People

5 O you who emigrates to Allah, convey the messages of your Lord to the people, perhaps it will prevent them from self-division and desires, and remind them of the remembrance of Allah, the Most High, the Great

\* Say, O my people, fear Allah, and do not shed blood, and do not interfere with yourself, and be among the righteous

\* Be careful not to corrupt the earth after its reformation, and do not follow the ways of the heedless

\* Among you are those who want to convey the command of their Lord, for it is appropriate for them to convey themselves first and then convey to the people so that their words appeal to the hearts of the listeners. Without that, their words will not affect the hearts of the seekers

\* Beware, O my people, that you are not from those who command people to righteousness and forget themselves, their words will be denied whenever it comes out of their mouths, then the realities of things, then the angels of the near

\* If the words of these people affect anyone, it is not because of them, but because of the potential within the words of an able and wise ruler

\* Their example before Allah is like a lamp from which the servants derive light, while it burns itself and becomes one of the burnt

\* Say, O my people, do not commit what would waste the sanctity of your worship and the sanctity of the command between the servants, and do not become one of the corrupt

\* Do not approach what your minds deny, avoid sin, and indeed it is forbidden to you in the book of which only those whom Allah has purified from all impurities and made from the purifiers can touch

\* Be just to yourselves and then to people, so that the effects of justice appear in your actions among our sincere servants

\* Beware not to betray people's money, be trustworthy among them, and do not deprive the poor of what Allah has given you from His bounty, and indeed He rewards those who spend twice what they spent, there is no god but He, He has the creation and the command, He gives to whoever He wills and prevents from whoever He wills, and indeed, He is the Giver, the Generous, the Almighty, the Noble.

6 Say, O people of splendor, convey the command of God, for God has ordained for every soul to convey His command and has made it the best of deeds, for it will not be accepted except after knowing God, the Dominant, the Mighty, the Powerful. And the conveyance is by explanation, not without it, just as the command came down from the dominion of God, the Most High, the Wise. Beware that you do not fight with yourself, but remind it of the good advice and the profound admonition if it is mindful, and if not, then turn away from it, and then turn to the direction of Holiness, the abode of the luminous sanctity.

And do not dispute for the world and what has been decreed in it for anyone, for God has left it for its people, and what He wanted from it was only the hearts of the servants, and indeed, it is controlled by the armies of revelation and explanation, just as the matter was ordained from the fingers of splendor on the tablet of destiny from the knowledgeable executor.

Be merciful to yourselves, then to your relatives, then to the sincere servants of God. And if you find someone humble, do not be arrogant towards them, for the authority of honor will pass over them in the course of days, and no one knows how that will be except for the one whose will is the Will of your Lord, the Mighty, the Wise.

7 My dear people, O wealthy ones, if you see a poor person of status, do not turn away from them but instead sit with them and inquire about their situation, as the blessings of God's judgment pour upon them. By Allah, in such cases, the people of the highest assembly will bear witness to you, pray for you, seek forgiveness for you, mention you, and praise you with holy, pure, and eloquent tongues.

\* So blessed is the scholar who does not take pride in his knowledge over others, and good is the doer of good who does not mock those who disobey but rather God conceals their faults, for He is the best of concealers.

\* Be, O people, concealing of faults and forgiving of sins on earth, so that God forgives you by His grace, then overlook so that God overlooks your sins and dresses you in the garment of beauty.

\* And if one of the believers seeks protection and you are able, protect them and do not deprive them of what they desire so that God protects you under the shadow of His mercy on the Day when hearts boil, livers ignite, and the foundations of all creation shake.

\* Say, O people, be sincere in truth for it will beautify your souls, elevate your names, and raise your status, and your reward in the Hereafter will be great based on the truth.

\* That is how we advise those who believe, so that they may hear our advice in the Book of God and find a way to the One of Bounty.

8 Oh you who have entered the great scene, your standing time has come to an end before the throne. With God's permission, rise and take the book of grace, then go to the homes and give their inhabitants the glad tidings of God's satisfaction, the high and great king. But move from this paradise with the breaths of intimacy to bring life to the hearts of those who were shocked by the lightning of the command, so that they may rise from the graves of negligence and speak what the spirit spoke that day in the highest paradise, that there is no god but Him, and the one who came in the name of Ali before the noble appearance of his authority and the emergence of his verses and the source of his grace and power for those in the heavens and the earth.

Then the one who speaks at that time, verily his might and honor, and his greatness and glory upon all creation. Thus, it is appropriate for you and those who have settled on the seat of the command and have drunk the sealed wine from this holy, luminous cup. And when you reach the land of T, spread this tablet before the hands of our generous name Ism, so that his eyes may be pleased, and he will rejoice in himself, and he will be among the joyful. Then before the hands of those who have emerged from the darkness of illusion and have settled on the seat of certainty, and there, you will hear the noise of those who have disbelieved, turned away, and been among the polytheists.

Say, oh people, have you disbelieved in God who created you, shaped you, and made you aware of His appearance and made you among the knowledgeable? Beware, oh people, do not deprive yourselves of the seas of meanings and do not follow every rebellious devil. Then look with the corner of holiness to the balance of God, so that you may know His true, straight balance. Say, today it is the right of every soul to purify its heart from attachment to what was created between the heavens and the earth, to sanctify its ear from all that it has heard, and to return its sight to what was before it from the evidence by which God revealed His command in every age and era, then to the evidence which appeared that day with a clear authority. And it is curious about the traces of God and reflects on them, I swear by God, as the sun of certainty rises on it from the eastern plane of its Lord, and its heart will be illuminated by it, and it will be one of the certain ones.

Say, the making of God will not be confused with the making of anyone among people, but people are confused about themselves, so why are they hardly able to understand a speech from God, the Mighty, the Expert? Say, after the sun rises and its light, will the light remain? No, by God, the Dominant, the Mighty, the Able. Thus, remember our command and complete the argument on everyone who is on the earth, all together. And we witness God and His chosen ones, then His angels, that I have not fallen short in all that I have been commanded to do, and I have delivered His messages to the east of the land and its west, and He and they are sufficient as a witness and knowing about me. And when you reach the land of Zz, remind the servants who were there with this great reminder. Say, oh people, believe in God and what has been revealed from Him, and do not follow those who have disbelieved in the signs of the Merciful and His authority, then remember Him in every early morning and evening.

Say, your example is like those who used to remember God in the evening and the morning, so when God came upon them on the shadow of His exalted name, they disbelieved in Him and were among the polytheists. Say, oh people, support God with yourselves and your money, then stand firm on His command, so that even if everyone on earth fought you, your feet would not be disturbed from the path of God, the Mighty, the Able, the Knowing. Stand firm, oh people, when Satan enters upon you and with him, what prevents people from the love of God and calls them to the greatest tyranny, and thus we inform you to be among the knowledgeable. I swear by God, the truth is that as soon as I heard in this matter the appearance of my irresistible, innovative affair, and we pointed it out to another wisdom from us, lest the hearts of the polytheists turn to a single seat, and the matter be preserved from the harm of every harmful stubborn one. And by God, who is no god but He, those who were to cover their faces from every watchful one when they rose against me with an injustice that could not be compared to the injustice of the first ones. And when you see Muhammad before Ali, give him glad tidings from us, then remind him of what was revealed to him in the tablets of might, protection.

Say, oh servant, stand firm on the command and do not associate anyone with God, then suffice with Him from everything else, and be on an impregnable straight path, cut off from everyone else, and commune with my remembrance, and do not be among those who deny. Stand on the specific worship, for by it is the command of God, your Lord, confirmed, and mercy descends upon the worlds. Say, oh people, do not harden the command of God by what your souls have suggested to you, nor go beyond your boundaries, nor be among the corrupt. And whoever transgresses his limit today will not be mentioned by God and will be one of the transgressors. Prostrate to God, your Lord, and when the sun of wisdom shines upon you from the east of the statement, fall on the ground in submission to your Lord, the Merciful, and thus it is appropriate for you, O assembly of the near ones. And whoever finds the pleasure of worship and its sweetness, will not change it for anything from what was created between the heavens and the two earths, and by it, your faces will be illuminated, your chests purified, your souls sanctified, and your traces elevated among the worlds. Then know that the most honorable among God are the most humble and pious, as has been revealed before and at that time, and we were revelatory.

Listen, oh people, to what God commands you in the kingdom of His command, and do not be among those who have been negligent in the side of God and have gone beyond what we have determined for them, for the residence of the transgressors is wretched.

9 Oh you who are present before the Throne, acquaint yourself with people with wisdom, then preserve yourself lest any harm befall you and return to the protected Sidra tree \[referring to a heavenly tree\]. Avoid matters that cause sedition, then seek your Lord's grace at all times. Beware not to forget these days; by Allah, they will not be matched in any time of both early and late generations. And no one will attain its meeting except by the will of your Lord; thus We have decreed the matter, and indeed, We are the Determiners. And do not forget the times you were present directly before the Throne in the greatest Paradise, and the sun of your Lord's beauty shone upon you at all times with wondrous lights; you drank the wine of the signs from the abundantly merciful Kuwthar, and you were granted blessings from Allah, the Giver, the Generous.

If you see someone approaching the Sacred House of Allah to enter the mighty Throne's residence, prevent them on our behalf, for by that the souls would be disturbed, and the harm would return to the Noble, the Knowledgeable. Do not direct yourself to part of Allah except after His permission, and thus the ruling appeared from the horizon of the wise command. Then convey the command of your Lord in every city; if you find someone cut off, give him the glad tidings of the mercy and presence of Allah, then remind him of what befell us from the forces of the devils. Say, "By Allah, what befell us is like nothing that ever happened to any of the servants, and by this, the clamor of every knowledgeable seer was raised."

Nothing has been created in the creation except that it might weep for my distress, and there is nothing in the knowledge of Allah if you are among the knowledgeable. Those whom I created by the will of my heart disbelieved in me and wrote for my rejection tablets by which their deeds were invalidated, and they shall not be among the poets. Thus the traces of Grace were effaced, the waters of mercy were cut off, the clouds of generosity were withheld, and the breezes of holiness were severed from the worlds.

Indeed, you shall recount the story of the youth as you have known it; do not increase or decrease, and be on the straight path of truth. Then inform the people of the fabrications of the selves of those who disbelieved and associated partners, say: "By Allah, what they intended by them is but to turn away the servants from the direction of the Throne, by Allah, they are but upon manifest misguidance." And when you reach the land of Mecca from Medina, remind Our people there among the submissive men and submissive women so that they may rejoice in their hearts and be among the joyful. Say: "By Allah, the Greatest Secret has appeared with the embroidery of Eternity, and with its word, when they depart from around it, the structures of the eminent ones collapse, and you, O people, are to remain steadfast on the command of Allah and His authority, and do not disbelieve in what you have believed in before, thus does the servant advise you at the time when suffering has encompassed him from all directions from the manifestations of the idolaters and he sat in prison and will find no helper for himself but Allah, the Competent, the Mighty, the Wise."

By Allah, the truth is that I have been killed at all times with all the swords, and none knows that but Allah, the Enumerator, the Wise.

10 O traveler, a tablet has been sent down before for the devout, which we have named the Tablet of Splendor. In it is mentioned what has been revealed to us indirectly. Take its essence, then go with it to them, and recite it to them so that they may remember what befell the youth from the armies of the devils. Say, O beloved of God, protect yourselves lest Satan turn you away from the remembrance of the Merciful. Then remember Him with the melodies of the attracted, for by His remembrance hearts are purified, souls refined, and the hearts of lovers attracted.

When you reach the pure servants of God, remind them of what has been sent down to us in this remote prison so that they may be partners in our afflictions, remember what has befallen us in these days, and be among the rememberers.\*

And when you have reached them, remind them of the Name of God, who was among the remaining members of the family of Hussein, between the heavens and the earth, those who sacrificed their lives in the way of God their Creator and were among the strugglers. Those who strived with their wealth and their selves for the sake of God, until they entered the paradise of the Merciful and were among the believers therein, where they will be adorned with the highest Paradise, and the most splendid youths will circle around them with cups of existence, and the virgins of honor will serve them in morning and evening.

Thus does God reward those who were martyred in His Cause and pay the rewards of those who were afflicted with hardships in His command. What a great reward for the strugglers!

Then turn to the other half of our Great Name by the Tablet of God and its trace, and enter it with a great announcement. Then remind it what the spirit cast upon you in this noble landscape. Then tell it the story of the youth so that it may be informed of what has befallen us in this remote prison, and may share in our tribulations and remember what has befallen us in these days, and be among the rememberers.

11 Say, O observer, look upon the greatest sight and do not forget the remembrance of your Lord. Stand upright on the command from Us and power from Our presence, and convey to the people what you have been commanded, and do not be among the patient ones. Seek help at all times from Allah, your Lord, and break through the veils of the deluded. Thus, we have ordered you before, and we order you now with clear signs, then remind those who were there among the devoted servants of Allah. Say, O people, stand up for the cause of Allah and His religion, then support it and be among the supporters. Then know that He is free from needing anything other than Himself, and what He commands for the people is a favor upon them, because through this they will ascend to the nearest place in the highest paradise and witness that every one with sharp sight. Thus, we have ordered you and decreed for you to act according to what you have been commanded, and be on clear justice. Allah will reward those who spread His command, and nothing will prevent them: no criticism from someone who finds fault, no taunting maliciousness, and none can withhold it nor a multitude of wrongdoers. When you see your brother who has been named in the kingdom of names Ahmad, remind him of the remembrance of his Allah, his Lord, then remind him of what has been revealed to us in this distant land. Say, O servant, beware of being alarmed in your soul when others are alarmed, whether small or great. Purify your sight from the veils, so you may witness what has shone from the horizon of the words of your Lord, the sun of meanings and clear explanation, and be among those who know. Be firm in the command of your Master, and do not turn to the right or left for this is a great favor. Settle in the shade of the tree and taste its fruits, and be among the grateful. We have commanded you thus to abandon what your own desire commands you and take what your Master commands you. By Allah, this is better for you if you are among the workers.

12 Indeed, you are, O you who are present at the Throne, and the observer of the great scene: reassure yourself with what you have been named in the realm of Names as Muhammad, and in the highest dominion as Mubaligh, and near the Throne as Mahmood. And thus, Allah singles out with His grace whom He wills, and He is indeed the Mighty, the Generous. Congratulations to you, for all the good, its origins, and sources you have attained and you are among those who have reached it. You have drunk the Tasneem of bounty from its source, and you are among the winners. So Allah will manifest the merit of what you have gained, and He will reward you for what you have done in His cause if you are a worker of what you have been commanded from the side of the all-knowing, the wise. And thus is completed your Lord's argument upon you and those who believe in Allah and His signs, and upon all who are in the two heavens and the two earths. When the pen of the Order ceases its motion, according to the wisdom that no one is acquainted with except Allah, the Mighty, the Beautiful, and praise be to Him in all circumstances, there is no god but He; creation and command belong to Him, and all shall return to Him.

{{< pagebreak >}}
